package codexadapter

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/HW-Yue/Memora/internal/skillcontract"
)

const Version = "memora.codex-adapter/v1"

type File struct {
	Content []byte
	Mode    os.FileMode
}

type Bundle struct {
	Files map[string]File
}

type Manifest struct {
	Version         string         `json:"version"`
	CanonicalDigest string         `json:"canonical_digest"`
	Files           []ManifestFile `json:"files"`
}

type ManifestFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Mode   string `json:"mode"`
}

func Build(canonicalDirectory string) (Bundle, error) {
	canonical, err := skillcontract.Load(canonicalDirectory)
	if err != nil {
		return Bundle{}, fmt.Errorf("build Codex adapter: %w", err)
	}
	if err := canonical.Validate(); err != nil {
		return Bundle{}, fmt.Errorf("build Codex adapter: %w", err)
	}
	skill := []byte(canonical.Markdown)
	contract, err := os.ReadFile(filepath.Join(canonicalDirectory, "contract.json"))
	if err != nil {
		return Bundle{}, fmt.Errorf("read canonical contract: %w", err)
	}
	installer, err := os.ReadFile(filepath.Join(canonicalDirectory, canonical.Contract.BootstrapScript))
	if err != nil {
		return Bundle{}, fmt.Errorf("read canonical bootstrap: %w", err)
	}
	files := map[string]File{
		".agents/skills/memora/SKILL.md":           {Content: skill, Mode: 0o644},
		".agents/skills/memora/contract.json":      {Content: contract, Mode: 0o644},
		".agents/skills/memora/scripts/install.sh": {Content: installer, Mode: 0o755},
		".agents/skills/memora/agents/openai.yaml": {Content: []byte(openAIMetadata), Mode: 0o644},
		".codex/rules/memora.rules":                {Content: []byte(commandRules), Mode: 0o644},
	}
	manifest := Manifest{Version: Version, CanonicalDigest: digest(skill), Files: manifestFiles(files)}
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return Bundle{}, fmt.Errorf("encode Codex adapter manifest: %w", err)
	}
	files["manifest.json"] = File{Content: append(encoded, '\n'), Mode: 0o644}
	return Bundle{Files: files}, nil
}

func (bundle Bundle) Install(root string) error {
	if !filepath.IsAbs(root) {
		return fmt.Errorf("install Codex adapter: destination must be absolute")
	}
	paths := sortedPaths(bundle.Files)
	for _, relative := range paths {
		file := bundle.Files[relative]
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create Codex adapter directory: %w", err)
		}
		temporary := path + ".tmp"
		if err := os.WriteFile(temporary, file.Content, file.Mode); err != nil {
			return fmt.Errorf("write Codex adapter file %q: %w", relative, err)
		}
		if err := os.Chmod(temporary, file.Mode); err != nil {
			_ = os.Remove(temporary)
			return fmt.Errorf("set Codex adapter mode %q: %w", relative, err)
		}
		if err := os.Rename(temporary, path); err != nil {
			_ = os.Remove(temporary)
			return fmt.Errorf("publish Codex adapter file %q: %w", relative, err)
		}
	}
	return nil
}

func (bundle Bundle) Compare(root string) error {
	for _, relative := range sortedPaths(bundle.Files) {
		want := bundle.Files[relative]
		path := filepath.Join(root, filepath.FromSlash(relative))
		got, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("Codex adapter artifact %q: %w", relative, err)
		}
		if string(got) != string(want.Content) {
			return fmt.Errorf("Codex adapter artifact %q drifted from generator", relative)
		}
		info, err := os.Stat(path)
		if err != nil || info.Mode().Perm() != want.Mode.Perm() {
			return fmt.Errorf("Codex adapter artifact %q mode drifted", relative)
		}
	}
	return nil
}

func manifestFiles(files map[string]File) []ManifestFile {
	paths := sortedPaths(files)
	entries := make([]ManifestFile, 0, len(paths))
	for _, path := range paths {
		file := files[path]
		entries = append(entries, ManifestFile{Path: path, SHA256: digest(file.Content), Mode: fmt.Sprintf("%04o", file.Mode.Perm())})
	}
	return entries
}

func sortedPaths(files map[string]File) []string {
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

func digest(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

const openAIMetadata = `interface:
  display_name: "Memora"
  short_description: "Query and maintain an auditable local personal database"
  default_prompt: "Use Memora to discover, query, or maintain my local semantic database."

policy:
  allow_implicit_invocation: true
`

const commandRules = `# Generated by the Memora Codex adapter. Bootstrap remains approval-gated.
prefix_rule(
    pattern = ["memora", ["assimilate", "doctor", "exec", "feedback", "maintain", "mutate", "query", "reflect", "schema"]],
    decision = "allow",
    justification = "Memora commands are constrained by the canonical Skill, MSQL guards, and local Policy.",
    match = [
        "memora doctor",
        "memora query SHOW DATABASES",
        "memora mutate --plan {}",
        "memora feedback --event {}",
    ],
    not_match = [
        "memora init",
        "memora daemon start",
        "/bin/sh install.sh --yes",
    ],
)
`
